# Generated by Django 2.1 on 2019-04-17 23:04

from django.db import migrations, models
import sequence_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', sequence_field.fields.SequenceField(help_text='The value does not match the specified pattern', verbose_name='Sequence')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Test model',
                'verbose_name_plural': 'Test models',
            },
        ),
    ]
