# Generated by Django 2.1.5 on 2019-04-18 02:46

from django.db import migrations
from sequence_field import settings


def initialize_default(apps, schema_editor):
    Sequence = apps.get_model('sequence_field', 'Sequence')
    Sequence.objects.create(key=settings.SEQUENCE_FIELD_DEFAULT_NAME,
                            template=settings.SEQUENCE_FIELD_DEFAULT_TEMPLATE)


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_field', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_default),
    ]
